package org.realityczech.app.ui

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalUriHandler
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import coil3.compose.AsyncImage
import org.realityczech.app.model.LearningResource
import org.realityczech.app.model.TranscriptLine

private const val PRONUNCIATION_IMAGE_KIND = "pronunciation image"

@Composable
fun LessonMediaSection(
    resources: List<LearningResource>,
    transcript: List<TranscriptLine>,
) {
    val videos = resources.filter { it.isEmbeddedVideo }
    val pronunciationImages = resources.filter { it.kind == PRONUNCIATION_IMAGE_KIND }
    val otherResources = resources.filterNot {
        it.isEmbeddedVideo || it.kind == PRONUNCIATION_IMAGE_KIND
    }

    if (videos.isNotEmpty()) {
        EmbeddedVideoSection(videos = videos, transcript = transcript)
    }

    if (pronunciationImages.isNotEmpty()) {
        PronunciationGallery(pronunciationImages)
    }

    if (otherResources.isNotEmpty()) {
        Text("Other sources", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
        otherResources.forEach { resource -> ExternalResourceCard(resource) }
    }

    if (videos.isEmpty() && transcript.isNotEmpty()) {
        StaticTranscript(transcript)
    }
}

@Composable
private fun PronunciationGallery(resources: List<LearningResource>) {
    val speaker = rememberCzechSpeaker()

    Text("See, listen, and repeat", style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold)
    Text(
        "These pictures are streamed from the original Reality Czech lesson. The voice is generated by your device’s Czech text-to-speech engine.",
        style = MaterialTheme.typography.bodySmall,
    )

    if (speaker.isUnavailable) {
        Text(
            "No Czech text-to-speech voice is installed on this device. Images remain available, but listening controls are disabled.",
            color = MaterialTheme.colorScheme.error,
        )
    }

    LazyRow(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
        items(resources, key = { "${it.title}-${it.url}" }) { resource ->
            PronunciationCard(resource = resource, speaker = speaker)
        }
    }

    ListenAndTypePractice(resources = resources, speaker = speaker)
}

@Composable
private fun PronunciationCard(
    resource: LearningResource,
    speaker: CzechSpeaker,
) {
    Card(Modifier.width(220.dp)) {
        Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
            AsyncImage(
                model = resource.url,
                contentDescription = resource.note.ifBlank { resource.title },
                modifier = Modifier.fillMaxWidth().height(140.dp),
                contentScale = ContentScale.Crop,
            )
            Column(
                modifier = Modifier.padding(start = 12.dp, end = 12.dp, bottom = 12.dp),
                verticalArrangement = Arrangement.spacedBy(6.dp),
            ) {
                Text(resource.title, style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold)
                if (resource.note.isNotBlank()) Text(resource.note)
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    Button(
                        onClick = { speaker.speak(resource.title) },
                        enabled = speaker.isReady,
                    ) { Text("Listen") }
                    OutlinedButton(
                        onClick = { speaker.speak(resource.title, slow = true) },
                        enabled = speaker.isReady,
                    ) { Text("Slow") }
                }
            }
        }
    }
}

@Composable
private fun ListenAndTypePractice(
    resources: List<LearningResource>,
    speaker: CzechSpeaker,
) {
    var selectedIndex by remember(resources) { mutableIntStateOf(0) }
    var answer by remember(selectedIndex) { mutableStateOf("") }
    var submitted by remember(selectedIndex) { mutableStateOf(false) }
    val item = resources[selectedIndex.coerceIn(resources.indices)]
    val correct = normalizeAnswer(answer) == normalizeAnswer(item.title)

    Text("Listen and type", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
    Card(Modifier.fillMaxWidth()) {
        Column(
            modifier = Modifier.padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(10.dp),
        ) {
            AsyncImage(
                model = item.url,
                contentDescription = item.note.ifBlank { "Vocabulary image" },
                modifier = Modifier.fillMaxWidth().height(180.dp),
                contentScale = ContentScale.Fit,
            )
            Text("Listen to the Czech word, then type it with the correct diacritics.")
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                Button(
                    onClick = { speaker.speak(item.title) },
                    enabled = speaker.isReady,
                ) { Text("Play word") }
                OutlinedButton(
                    onClick = { speaker.speak(item.title, slow = true) },
                    enabled = speaker.isReady,
                ) { Text("Play slowly") }
            }
            OutlinedTextField(
                value = answer,
                onValueChange = {
                    answer = it
                    submitted = false
                },
                modifier = Modifier.fillMaxWidth(),
                label = { Text("Czech word") },
                singleLine = true,
            )
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                Button(
                    onClick = { submitted = true },
                    enabled = answer.isNotBlank(),
                ) { Text("Check") }
                OutlinedButton(
                    onClick = {
                        selectedIndex = (selectedIndex + 1) % resources.size
                        answer = ""
                        submitted = false
                    },
                ) { Text("Another word") }
            }
            if (submitted) {
                Text(
                    if (correct) "Correct. ${item.title} means ${item.note}." else "Not yet. The answer is ${item.title}.",
                    color = if (correct) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.error,
                )
            }
        }
    }
}

@Composable
private fun EmbeddedVideoSection(
    videos: List<LearningResource>,
    transcript: List<TranscriptLine>,
) {
    var selectedIndex by remember(videos) { mutableIntStateOf(0) }
    var transcriptVisible by remember { mutableStateOf(false) }
    var seekSeconds by remember { mutableStateOf<Int?>(null) }
    val selectedVideo = videos[selectedIndex.coerceIn(videos.indices)]
    val selectedTranscript = transcript.filter {
        it.mediaId.isBlank() || it.mediaId == selectedVideo.mediaId
    }

    Text("Watch and listen", style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold)

    if (videos.size > 1) {
        Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
            videos.forEachIndexed { index, video ->
                if (index == selectedIndex) {
                    Button(
                        onClick = { selectedIndex = index },
                        modifier = Modifier.fillMaxWidth(),
                    ) { Text(video.title) }
                } else {
                    OutlinedButton(
                        onClick = {
                            selectedIndex = index
                            transcriptVisible = false
                            seekSeconds = null
                        },
                        modifier = Modifier.fillMaxWidth(),
                    ) { Text(video.title) }
                }
            }
        }
    } else {
        Text(selectedVideo.title, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
    }

    YouTubePlayer(
        videoId = selectedVideo.mediaId,
        seekToSeconds = seekSeconds,
    )

    if (selectedVideo.note.isNotBlank()) {
        Text(selectedVideo.note, style = MaterialTheme.typography.bodySmall)
    }

    val uriHandler = LocalUriHandler.current
    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
        if (selectedTranscript.isNotEmpty()) {
            TextButton(onClick = { transcriptVisible = !transcriptVisible }) {
                Text(if (transcriptVisible) "Hide transcript" else "Show transcript")
            }
        }
        TextButton(onClick = { uriHandler.openUri(selectedVideo.url) }) {
            Text("Open source page")
        }
    }

    if (transcriptVisible) {
        Text(
            "Listen once before relying on the transcript.",
            style = MaterialTheme.typography.bodySmall,
        )
        selectedTranscript.forEach { line ->
            TranscriptRow(
                line = line,
                onSeek = line.startSeconds?.let { seconds -> { seekSeconds = seconds } },
            )
        }
    }
}

@Composable
private fun StaticTranscript(transcript: List<TranscriptLine>) {
    var visible by remember { mutableStateOf(false) }
    TextButton(onClick = { visible = !visible }) {
        Text(if (visible) "Hide transcript" else "Show transcript")
    }
    if (visible) transcript.forEach { line -> TranscriptRow(line = line, onSeek = null) }
}

@Composable
private fun TranscriptRow(
    line: TranscriptLine,
    onSeek: (() -> Unit)?,
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .then(if (onSeek != null) Modifier.clickable(onClick = onSeek) else Modifier)
            .padding(vertical = 8.dp),
    ) {
        if (line.speaker.isNotBlank()) {
            Text(line.speaker, style = MaterialTheme.typography.labelMedium)
        }
        Text(line.czech, fontWeight = FontWeight.Bold)
        if (line.english.isNotBlank()) Text(line.english)
        if (line.note.isNotBlank()) Text(line.note, style = MaterialTheme.typography.bodySmall)
        if (onSeek != null) Text("Tap to replay this segment", style = MaterialTheme.typography.labelSmall)
        HorizontalDivider(Modifier.padding(top = 8.dp))
    }
}

@Composable
private fun ExternalResourceCard(resource: LearningResource) {
    val uriHandler = LocalUriHandler.current
    Card(Modifier.fillMaxWidth()) {
        Column(Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
            Text(resource.title, fontWeight = FontWeight.Bold)
            Text(resource.kind, style = MaterialTheme.typography.labelMedium)
            if (resource.note.isNotBlank()) Text(resource.note, style = MaterialTheme.typography.bodySmall)
            TextButton(onClick = { uriHandler.openUri(resource.url) }) { Text("Open") }
        }
    }
}

private fun normalizeAnswer(value: String): String = value
    .trim()
    .lowercase()
    .trimEnd('.', '!', '?')
    .replace(Regex("\\s+"), " ")
